# Generated by Django 3.1.6 on 2021-02-18 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(default='profile_photo/default/DOWITH.png', upload_to='profile_photo/%Y/%m/%d/'),
        ),
    ]
