# Generated by Django 3.1.6 on 2021-02-20 17:38

from django.db import migrations, models
import login.models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=255, unique=True, verbose_name='이메일(ID)'),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default='profile_photo/default/DOWITH.png', upload_to='profile_photo/%Y/%m/%d/', verbose_name='프로필 사진'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_ToS',
            field=models.BooleanField(default=False, validators=[login.models.is_ToS], verbose_name='약관 동의'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_social',
            field=models.BooleanField(default=False, verbose_name='소셜 계정'),
        ),
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(max_length=100, unique=True, verbose_name='닉네임'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=150, verbose_name='이름'),
        ),
    ]
