# Generated by Django 3.1.6 on 2021-02-21 11:01

from django.db import migrations, models
import login.models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20210221_0239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(max_length=100, validators=[login.models.nickname_unique], verbose_name='닉네임'),
        ),
    ]
