<<<<<<< HEAD
<<<<<<< HEAD
# Generated by Django 3.1.6 on 2021-02-10 09:12
=======
# Generated by Django 3.1.6 on 2021-02-14 05:43
>>>>>>> challengeSearch_insong
=======
# Generated by Django 3.1.5 on 2021-02-14 17:03
>>>>>>> jihyun

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Friendship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted', models.BooleanField(default=False)),
            ],
        ),
    ]
