# Generated by Django 3.1.6 on 2021-02-15 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friend', '0003_motivation'),
    ]

    operations = [
        migrations.AddField(
            model_name='motivation',
            name='count',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
