<<<<<<< HEAD:challenge/migrations/0002_auto_20210208_1519.py
# Generated by Django 3.1.6 on 2021-02-08 15:19
=======
# Generated by Django 3.1.6 on 2021-02-06 08:47
>>>>>>> jimin:challenge/migrations/0002_enrollment_player.py

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('challenge', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_set', to=settings.AUTH_USER_MODEL, verbose_name='유저'),
        ),
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together={('challenge', 'player')},
        ),
    ]
