# Generated by Django 3.1.6 on 2021-02-14 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0002_auto_20210213_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='status',
            field=models.IntegerField(blank=True, choices=[(0, '대기 중'), (1, '진행 중'), (2, '완료')], null=True, verbose_name='진행 상태'),
        ),
    ]
