# Generated by Django 3.1.5 on 2021-02-14 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0002_auto_20210215_0203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challenge',
            name='link_url',
        ),
        migrations.AddField(
            model_name='challenge',
            name='invitation_key',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
