# Generated by Django 3.1.6 on 2021-02-18 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0002_auto_20210219_0034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='cur_pp',
            field=models.IntegerField(default=0),
        ),
    ]
